"""Initial migration.

Revision ID: 81f06d2c7c17
Revises:
Create Date: 2024-03-09 23:00:00.544511

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "81f06d2c7c17"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=60), nullable=False),
        sa.Column("_hash", sa.String(length=60), nullable=False),
        sa.Column("content_type", sa.String(length=60), nullable=False),
        sa.Column("create_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("edit_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("image")
    # ### end Alembic commands ###
